### PR TITLE
Extensions - Fix variable shadowing

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Try to fix Multipath issues.

### CODE REVIEW

**Comment by jonpas** [comment]
Does **not** fix signal calculation issues on LOS Multi-Path. Repeated same test as we did without the fix, distance up to 2km and over the hill, no matter the distance, 343 stays at -35 dB, 152 at -18 dB.

LOS Simple still works better, but still at -81 dB at 2km.

**Comment by jonpas** [comment]
Confirmed again, 343 works even at 10km behind smaller hills (cut-off over large hills works fine).

**Comment by jonpas** [comment]
863e92e8273e4853aa9d567acdf6be76ae5e98d3 broken (1007+ - includes ACRE2Shared cleanup)
33105a1b1328d33873971b9d6dfdcc112705e126 broken (1007+)
4a88705af056624c4a4db95954e04f3d23b09ea4 broken (1007)
0cc8fbf98edd6db2f28861e208872820867e9bbf works (2.6.4.1006 release)

There are only 2 commits between 1006 and 1007 builds:
- eb8ee2035aa39a87848da818908f08a36c904314 unlikely this breaks anything
- 569e64c5448b28a1c5bf89b393492e8f8ea4e6d9 a lot more likely this does!

**Comment by jonpas** [comment]
There are more commits from 2.6.0 to 2.7.0 in 1007 that were not part of hotfixes due to branch diversion.

- Longley-Rice is NOT the cause
- FakeWRP new program is NOT the cause

Investigation continues...

**Comment by jonpas** [comment]
7ab7ba89c7815a6e1e3e4c169246dc34867edb0c still broken

Before that requires TS roll-back.

**Comment by Soldia1138** [comment]
@TheMagnetar Do you want it merged even if #925 fixes the issue?

**Comment by jonpas** [comment]
Title needs to be changed before merge.

**Review by jonpas — APPROVED** [review]

**Pull request merged**
