### PR TITLE
ACRE2Shared cleaning

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Cleaning of  ACRE2Shared
  - Remove dependency of  MSVC concurrent_queue. All its use was thread locked so no performance loss
  - Remove of Windows specific time getters and use chrono  instead.
  - Remove  WriteFile and CriticalSection in Log and use C++ native functions.
- ACRE2TS and distortion plugin: Remove dependency of  MSVC concurrent_queue since it was not used at  all

### CODE REVIEW

**Comment by kymckay** [comment]
Admittedly I have next to no C++ experience, but rather than checking conditions to return booleans, couldn't you just return one big boolean conditional?

**Comment by TheMagnetar** [comment]
You would have to still go through all the conditions and code is easier  to  understand in this way.

**Comment by TheMagnetar** [comment]
This is ready for review

**Review by jonpas — APPROVED** [review]

**Review by NouberNou — APPROVED** [review]
Looks good, pending testing.

**Comment by NouberNou** [comment]
> Admittedly I have next to no C++ experience, but rather than checking conditions to return booleans, couldn't you just return one big boolean conditional?

It'd look the same to the compiler, this is just a more explicit and cleaner way to write a very long `&&`ed together boolean statement.

**Comment by TheMagnetar** [comment]
Tested locally @NouberNou. I need a partner for that.

**Pull request merged**
