### PR TITLE
Translation - Add and Improve Portuguese

### PR DESCRIPTION
**Pull request by BifeO**
Translation to Portuguese. The Brazilian Portuguese was used, but I tried to make it understandable for all worldwide variations of Portuguese.
A review is needed, mostly for non-Brazilian players that speak Portuguese and for typing errors.
I've made some changes to the existing lines due to incorrect or inappropriate translation/word choice.

Thank you.

**When merged this pull request will:**
- Describe what this pull request will do
- Each change in a separate line
- Respect the [SQF](http://acre2.idi-systems.com/wiki/development/coding-guidelines-sqf) and [C++](http://acre2.idi-systems.com/wiki/development/coding-guidelines-cpp) Coding Guidelines
- Follow title standard `System - Add|Fix|Improve|Change|Make|Remove radios`

### CODE REVIEW

**Comment by BifeO** [comment]
I had a problem. Couldn't edit "sys_intercom" lines because of this: [https://imgur.com/etF66fI](url). It's the only issue and I didn't mention it earlier because I was still trying to bypass it. No success, so I'm warning everyone that translation is incomplete.

**Comment by BifeO** [comment]
I had a problem. Couldn't edit "sys_intercom" lines because of this: https://imgur.com/etF66fI. It's the only issue and I didn't mention it earlier because I was still trying to solve it. No success, so I'm warning everyone that translation is incomplete.

**Comment by PabstMirror** [comment]
I fixed the bad strings that were blocking tabler from loading.
The changes were pushed to your fork of acre.
You will want to "Fetch" and "Pull" on your local copy, which should then allow you to open tabler and continue editing

Please let me know if you have any problems

**Comment by BifeO** [comment]
All done. Thanks!!!

**Review by TheMagnetar — APPROVED** [review]
Seems OK! Thanks

**Comment by BifeO** [comment]
> Seems OK! Thanks

NP! Let me know if I can help with anything else.

**Review by jonpas — APPROVED** [review]
Thanks!

**Pull request merged**
