### PR TITLE
117F - Fix auto-start on interface open when turned off

### LINKED ISSUE #913: Turned off 117F auto-starts on interface open (+ script error)
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` stable
- **CBA:** `3.15.0` stable
- **ACRE2:** `2.7.2+` **development**
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**

**Steps to reproduce:**
- Open 117F UI
- Turn 117F to "OFF"
- Close 117F UI
- Open 117F UI
- Observe radio auto-starting (knob still on "OFF") and throwing below script error.

**Expected behavior:**
117F should not auto-start on UI open.

**Where did the issue occur?**
- Dedicated (auto-start + script error) / Editor (just auto-start)

**Log Files:**
```
isplay;

private _menuId = (_menu select 0);
if (isNil "_menuId") then {
(>
16:58:34   Error position: <select 0);
if (isNil "_menuId") then {
(>
16:58:34   Error Generic error in expression
16:58:34 File idi\acre\addons\sys_prc117f\menus\fnc_renderMenu.sqf..., line 24
```

**Additional context:**
/

**Screenshots:**
/

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Fix #913 

Equivalent to 152 now.

### CODE REVIEW

**Comment by jonpas** [comment]
Tested working.

**Review by Soldia1138 — APPROVED** [review]
LGTM

**Comment by Soldia1138** [comment]
Do you wanna fill the file comment on top?

**Comment by jonpas** [comment]
@Soldia1138 done.

**Pull request merged**
