### PR TITLE
Intercom - Improve Infantry Phone Limitations and add Custom Positions to Vanilla Vehicles

### PR DESCRIPTION
**Pull request by mrschick**
**When merged this pull request will:**
- Hide Infantry Phone interaction on destroyed vehicles;
- Return Infantry Phone when going unconscious;
- Add Infantry Phone to ~~`Wheeled_APC_F` class inheritors~~ Vanilla Wheeled APCs;
- **Add Custom Infantry Phone position on Vanilla vehicles:**
    - `Wheeled_APC_F` inheritors:
        - NATO AMV-7 Marshall (Badger IFV);
        - NATO Rhino MGS Tank Destroyer (Rooikat 120);
        - CSAT MSE-3 Marid (Otokar ARMA);
        - AAF AFV-4 Gorgon (Pandur II);
    - `Tanks` inheritors: 
        - CSAT T-100X Futura;
        - CSAT T-140 Angara (T-14 Armata);
        - AAF AWC 301/304 Nyx (Wiesel 2);

### CODE REVIEW

**Comment by Drofseh** [comment]
Adding the infantry phone to Wheeled_APC_F should not be done.
This will create a ton of work to *remove* infantry phones from vehicles that should not have them.
For example, these are the CUP vehicles that inherit from Wheeled_APC_F and most if not *all* of them should not have an infantry phone.
```sqf
class CUP_BRDM2_Base: Wheeled_APC_F
class CUP_BTR40_MG_Base: Wheeled_APC_F
class CUP_BTR60_Base: Wheeled_APC_F
class CUP_BTR80_Common_Base: Wheeled_APC_F
class CUP_BTR90_Base: Wheeled_APC_F
class CUP_Boxer_Base: Wheeled_APC_F
class CUP_GAZ_Vodnik_Base: Wheeled_APC_F
class CUP_LAV25_Base: Wheeled_APC_F
class CUP_Mastiff_Base: Wheeled_APC_F
class CUP_Ridgback_Base: Wheeled_APC_F
class CUP_StrykerBase: Wheeled_APC_F
class CUP_Wolfhound_Base: Wheeled_APC_F
```

**Comment by mrschick** [comment]
I suspected there was a reason they didn't have InfPhones 🤔
Do most of those vehicles really not have infantryphones but do have crew ~~/pax~~ intercoms?

Either way, should be easy enough to work around by adding the full infantry phone config to each Vanilla APC class.

**Comment by mrschick** [comment]
Should be good like this, on `Wheeled_APC_F` I defined Infantry Phone as disabled + other normal attributes to avoid having to duplicate them on every child class. That way it only has to be enabled and be set to custom position on each APC.
Tested it and without `acre_hasInfantryPhone = 1;` in a child class the vehicle has no Infantry Phone at all, as expected.

**Comment by Drofseh** [comment]
> Do most of those vehicles really not have infantryphones but do have crew ~/pax~ intercoms?

99% of vehicles don't have infantry phones, even for tanks

**Review by Mike-MF — APPROVED** [review]
Tested, didn't see any issues.

**Review by jonpas — APPROVED** [review]

**Pull request merged**
