### PR TITLE
Remove intercom/Infantry phone from UAV and UGV vehicles

### LINKED ISSUE #379: Drones have Infantry Phone
As it can be seen in this picture, drones (at least the darter) got the infantry phone. 😄 

https://images-ext-2.discordapp.net/external/jqlrr88kZwfrwVfR9sY6BNUFJBkCFu567YsyVMcxdV8/https/i.imgur.com/8sBIdicr.jpg

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Title
- Closes #379

### CODE REVIEW

**Comment by jonpas** [comment]
Do we really need to redefine all of that instead of just setting the main entries?

**Comment by Sniperhid** [comment]
An easier method would be test if the vehicle is a UAV with either `unitIsUav` script command which apparently just looks up if the `isUAV` config property on the vehicle config which is true for all the vanilla vehicles.

I'd suggest a `if (unitIsUav _target) exitWith {};` in -> https://github.com/IDI-Systems/acre2/blob/master/addons/sys_intercom/fnc_intercomConfig.sqf

**Comment by Soldia1138** [comment]
Are UGVs counted as `unitIsUav` as well? If so, I would stick with magnetars proposal. Heading for autonomous racks

**Comment by jonpas** [comment]
> Are UGVs counted as `unitIsUav` as well?

It should be, it has `isUav = 1` in config and that's basically what the command does.

**Comment by TheMagnetar** [comment]
Done in overhauled system.

**Comment by jonpas** [comment]
Done in #411.

**Pull request closed without merging**
