### PR TITLE
Add local event when acre is initialised

### LINKED ISSUE #652: Add Event Handler for finished ACRE2 initialization
To be used by mission makers instead of checking `acre_api_fnc_isInitialized` in `waitUntilAndExecute`.

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Adds a local event when acre is initialised.
- Closes #652 

- @jonpas can you test?

### CODE REVIEW

**Comment by jonpas** [comment]
To check: what happens if event is thrown before client adds event handler.

Solution if nothing: add event handler in preInit.

**Comment by jonpas** [comment]
Needs documentation (and updating of examples).

**Comment by jonpas** [comment]
This doesn't really work, event is thrown before anything registers for it.

**Review by jonpas — CHANGES_REQUESTED** [review]
This doesn't really work, event is thrown before anything registers for it.

**Comment by TheMagnetar** [comment]
Close then?

**Pull request closed without merging**
