### PR TITLE
Allow Helicopter 'Gunner' Copilot to access racks

### LINKED ISSUE #633: ACRE2 'gunner' copilot rack access
**Arma 3 Version:** `Latest stable` (stable / rc / dev)
**CBA Version:** `Latest stable ` (stable / dev + commit hash)
**ACRE2 Version:** `Latest Stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- RHS USAF
```

The copilot, should have access to vehicle radio, normally the one using the radio is not the pilot for obious reasons :P. 
Any way I can add that ability to the copilot?

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Close #633

### CODE REVIEW

**Comment by TheMagnetar** [comment]
You can provide compat patches and they can be shipped with acre2. However we cannot maintain them, and the approach will be the same as with ace3

**Comment by jonpas** [comment]
Tested on vanilla Comanche, works fine.

**Comment by TheMagnetar** [comment]
Does it show rpt warnings If there is no gunner?

**Comment by jonpas** [comment]
@TheMagnetar None that I see, spawning a MH-6 NATO and Civilian Little Birds.

**Review by TheMagnetar — APPROVED** [review]

**Pull request merged**
