### PR TITLE
God Mode - Fix `sendText`

### PR DESCRIPTION
**Pull request by diwako**
**When merged this pull request will:**
- Adresses #1023

### CODE REVIEW

**Review by TheMagnetar — APPROVED** [review]

**Comment by jonpas** [comment]
I know it's Hacktoberfest rush, but next time you can still name the PR properly. :D

**Review by jonpas — APPROVED** [review]

**Comment by diwako** [comment]
> I know it's Hacktoberfest rush, but next time you can still name the PR properly. :D

I actually thought I named it properly... D:

**Comment by jonpas** [comment]
`<component> - Fix/Add/Remove/... <thing>`
Not that hard. :D

**Comment by diwako** [comment]
Chalk it up to first time making a PR to acre.

**Pull request merged**
