### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by classicarma**
- improve, fix and tweak to translation
- support to new entries

### CODE REVIEW

**Review by jonpas — APPROVED** [review]

**Comment by TheMagnetar** [comment]
Your PR contains conflicts. Would you mind solving them before merging it into master?

**Comment by jonpas** [comment]
Don't worry about it if you don't know how, I can handle it.

**Comment by classicarma** [comment]
completely I don't know how fix the conflicts. Please deal with this. thank you

**Comment by jonpas** [comment]
@classicarma I opened a pull request with latest changes properly merged in #532. Can you take a look and see if all is correct? Some strings already existed (by you and someone else).

**Comment by jonpas** [comment]
Merged in #532.

**Pull request closed without merging**
