### PR TITLE
Racks no longer use lowercase unique ids

### LINKED ISSUE #345: Lower case radio
- Treat all radios as lower case. At the moment the system is a mix of upper/lower case. fnc_MasterIDtracker handles them lowercase as well as sys_rack. This will ensure consistency.

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- No lower case treatment of radio IDs
- Closes #345

### CODE REVIEW

**Comment by jonpas** [comment]
Should we note that in some comment somewhere or on the wiki?

**Comment by TheMagnetar** [comment]
No. This is just internal. It does not affect any public function or file.

**Comment by jonpas** [comment]
No, it matters to developers.

Would lower-case radio class cause issues with this?

**Comment by TheMagnetar** [comment]
No. This is just how racked radios and racks were treated (internally) before. Nothing else. Racks function as before, only that the unique IDs got  converted internally to be lower case. This is no longer the case so that we avoid having to  convert them to lower case in order to avoid duplicates.

**Review by jonpas — DISMISSED** [review]

**Comment by jonpas** [comment]
Delaying because this needs a way closer look to make sure people can still use either case without breaking the whole system.

**Pull request closed without merging**
