### PR TITLE
Update Chinese Simplifed translations

### PR DESCRIPTION
**Pull request by RonaldBobo**
Chineseimp 中文简体

**When merged this pull request will:**
- Describe what this pull request will do
- Each change in a separate line
- Respect the [SQF](http://acre2.idi-systems.com/wiki/development/coding-guidelines-sqf) and [C++](http://acre2.idi-systems.com/wiki/development/coding-guidelines-cpp) Coding Guidelines

### CODE REVIEW

**Comment by RonaldBobo** [comment]
Update chineseimp translation

**Comment by bux** [comment]
@RonaldBobo Take a look at the Changes you've made.
There's something wrong with it.
image

**Comment by RonaldBobo** [comment]
What kind of question is it? I can't see the picture here




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jo David"<notifications@github.com&gt;; 
发送时间: 2020年1月9日(星期四) 晚上9:55
收件人: "IDI-Systems/acre2"<acre2@noreply.github.com&gt;; 
抄送: "雪风"<2973915867@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [IDI-Systems/acre2] Chineseimp (#877)




@RonaldBobo Take a look at the Changes you've made.
 There's something wrong with it.

**Comment by RonaldBobo** [comment]
image

**Comment by jonpas** [comment]
Will wait for #863 to merge due to further conflicts.

**Comment by RonaldBobo** [comment]
thank you

**Review by TheMagnetar — APPROVED** [review]
Looks fine

**Pull request merged**
