### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Change the following entries (done using grep command) according to coding guidelines:
  - `if(` to `if (`
  - `private[` to `private [`
  - `params[` to `params [`
  - `switch(` to `switch (`
  - `getVariable[` to `getVariable [`
  - `setVariable[` to `setVariable [`
  - `getNumber(` to `getNumber (`
- Identation of If statement in addons/sys_prc343/functions/fnc_onPTTHandlePress.sqf

### CODE REVIEW

**Comment by TheMagnetar** [comment]
Should commands like `getNumber(` also be formatted like `getNumber (`?

**Comment by jonpas** [comment]
Ooh, very nice, wanted to do that today! :D

Yes, it should be the same. I'll add more examples to the doc, all those PRs and questions make for perfect guidelines additions! :+1:

**Comment by TheMagnetar** [comment]
Done. This is all I could find. There may be some corner cases here and there, but so far I have not spotted any of those.

**Comment by jonpas** [comment]
It's great, I'll review later. 👍

**Review by jonpas — APPROVED** [review]

**Comment by jonpas** [comment]
Tested in MP, works fine.

**Review by Sniperhid — APPROVED** [review]
Tested with Jonpas

**Pull request merged**
