### PR TITLE
No verb at the beginning for radio states

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- As discussed in another PR. Changes radio states from having a verb at the beginning: "isShared" to "radioShared", ...

### CODE REVIEW

**Comment by jonpas** [comment]
This seems pretty redundant to me, all it does is make the event names longer. If those are passed over network, shorter is better, and just having `radio` everywhere seems rather weird, no?

**Comment by TheMagnetar** [comment]
Shorter messages do not mean faster messages. Often in networking a minimum message size is specified or, you combine several messages that need to be sent into a single one.

**Comment by jonpas** [comment]
"Often", this is Arma, this is the reason CBA uses short names such as "sCBA" for internal events. It shouldn't matter here either way.

**Comment by Soldia1138** [comment]
Well. It's not necessary. There was a reason for this but I don't remember anymore. Can delete/postpone this.

**Review by Soldia1138 — APPROVED** [review]

**Review by Sniperhid — APPROVED** [review]

**Pull request merged**
