### PR TITLE
Add Steam Workshop GM Compatibility and Dev Build release destinations

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Add Global Mobilization Compatibility to Steam Workshop manifest (for CI)
- Add Dev Builds to Steam Workshop manifest (for CI)
  - Use `master` branch commit history as changelog URL
- Fix "GitHub" capitalization

### CODE REVIEW

**Comment by jonpas** [comment]
This will let us publish Dev Builds on Workshop.

**Review by TheMagnetar — APPROVED** [review]

**Comment by TheMagnetar** [comment]
Hmm, i am unsure regarding dev-builds... I would not expose them too much. We do not advertise them on BI forums either, so better keep them in slack only. I leave this decision to you though.

**Comment by jonpas** [comment]
This is just publishing to an already existing Workshop item @TheMagnetar. And this way we can use it easier ourselves. If we make them public, we'll see.

**Comment by jonpas** [comment]
Also, this will help us identify Workshop upload issues or agreement updates.

**Pull request merged**
