### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by sdsznsk**
I've translated almost everything. The only thing I can't translate is STR_ACRE_sys_radio_noTransmitIntercom , since I don't know context or what it does. Please keep in mind that I'm not a professional translator ;)

**When merged this pull request will:**
- Add polish translation for most strings

### CODE REVIEW

**Review by TheMagnetar — APPROVED** [review]
Looks good.

**Comment by jonpas** [comment]
> The only thing I can't translate is STR_ACRE_sys_radio_noTransmitIntercom , since I don't know context or what it does.

That the rack currently can't transmit over intercom as well. @TheMagnetar that string could probably be written in a better way.

**Comment by TheMagnetar** [comment]
Well it essentially means that the radio cannot be used to transmit when being connected to that intercom. There are some intercom stations where such functionality is not available.

**Comment by jonpas** [comment]
@Teqashi I will merge this, you can fill out the remaining string in a separate PR.

**Pull request merged**
