### PR TITLE
Fix mismatched TS plugin and mod versions error formatting

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Use correct macro that supports new-lines for on-screen error message.

### CODE REVIEW

**Comment by Sniperhid** [comment]
Is there a way for a mod to specify a required CBA version? Might be nice to throw that in too if it exists.

**Review by Sniperhid — APPROVED** [review]
LGTM, see my comment though

**Comment by thojkooi** [comment]
@Sniperhid https://github.com/IDI-Systems/acre2/blob/master/addons/main/script_mod.hpp#L14

and it's used here: https://github.com/IDI-Systems/acre2/blob/master/addons/main/CfgSettings.hpp

**Comment by jonpas** [comment]
Yeah, I already answered him on Slack. I should start getting used to this GitHub being more public. 😆

**Comment by jonpas** [comment]
CBA 3.1.1 is actually not needed as we don't have anything else we want to display in big orange box at the moment.

**Pull request merged**
