### PR TITLE
Remove DFUNC and DEFUNC macros

### LINKED ISSUE #215: Document and reimplement D(E)FUNC macros
~~https://github.com/IDI-Systems/acre2/blob/fb6ce402358ede72d11484ef752d0fd93a63a6e6/addons/main/script_macros.hpp#L79-L80
are just copies of `(E)FUNC`, once all PRs convert we should just remove them.~~

Document `D(E)FUNC` properly with the "definite function" use case.

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Remove D(E)FUNC macros since they are duplicates of (E)FUNC.
- Closes #215.

- [x] Remove D(E)FUNC macro copies.
- [ ] Update documentation accordingly.

### CODE REVIEW

**Comment by NouberNou** [comment]
There was a purpose to having these, in that when used they will register the functions without wrapping them in possible debugging wrappers used when stack tracing is turned on... If we plan to never use the stack tracing functionality in CBA macros then this is fine to remove, but otherwise there was a purpose for this.

**Comment by jonpas** [comment]
Which is why I didn't do that yet, but forgot to comment on the issue.

**Comment by jonpas** [comment]
Going to leave those and rather document them properly, I edited the issue.

Hope you used search and replace anyways. 😆

**Comment by TheMagnetar** [comment]
No, I did it manually over the whole night! :(

**Pull request closed without merging**
