### PR TITLE
Clean-up and document to sys_io

### PR DESCRIPTION
**Pull request by Sniperhid**
**When merged this pull request will:**
- Remove unused functions (also they were broken)
- Document all function headers in sys_io.
- Minor speed improvements

### CODE REVIEW

**Comment by Soldia1138** [comment]
Comment above is valid for all descriptions

**Comment by jonpas** [comment]
@Sniperhid was this tested?

**Comment by Sniperhid** [comment]
In single player local testing seemed to go okay

**Comment by jonpas** [comment]
Tested local MP, works fine.

**Review by jonpas — APPROVED** [review]

**Pull request merged**
