### PR TITLE
Racks - Add an additional rack to helicopters

### PR DESCRIPTION
**Pull request by Mike-MF**
- Adds Rack 2 to helicopters
- Stringtabled Rack 2 on Planes.

### CODE REVIEW

**Comment by jonpas** [comment]
We've discussed this one some issue before, but planes and helicopters should have at minimum 2 racks across the board. I am not sure on 3, since it's harder to delete one than add one, but we might as well?

**Comment by BrettMayson** [comment]
Internally I've always had at least two on any military vehicle at large events. I think multiple for aircraft is a good step but I think 3 is unrealistic, most aircraft have COM1 and COM2. Not against per se, just a note.

**Comment by jonpas** [comment]
A lot have 3 (A-10C, Huey, Gazelle) etc, but I tend to agree 2 is better overall.

**Comment by BrettMayson** [comment]
Ah yeah good point, I'm fine with either though

**Review by jonpas — APPROVED** [review]

**Review by TheMagnetar — CHANGES_REQUESTED** [review]
There is already upper dash and lower dash. Why add another term (Rack 2) just for helicopters?

**Comment by jonpas** [comment]
> Why add another term (Rack 2) just for helicopters?

It doesn't. "Rack 2" already existed for planes as you can see in the config, it was just not stringtabled.

1/2 or Upper/Lower, doesn't make a difference to me, so whichever.

**Review by TheMagnetar — APPROVED** [review]
My bad. Mobile is not the best platform

**Pull request merged**
