### PR TITLE
GUI - Hide antenna display in cargo seat or no radio

### PR DESCRIPTION
**Pull request by PabstMirror**
**When merged this pull request will:**
- Fix  - `stance player` will be `"undefined"` when in vehicles
- Hide antenna display when player has no radios

### CODE REVIEW

**Review by jonpas — APPROVED** [review]

**Comment by Drofseh** [comment]
Could you also hide it when the player has no radio plz

**Comment by PabstMirror** [comment]
I think that would be fixed by also exiting if `{EGVAR(sys_radio,oldUniqueItemList) isEqualTo []}` but I'm not positive if that's safe

**Comment by Drofseh** [comment]
`{call acre_api_fnc_getCurrentRadio == ""}` should also do it

**Comment by jonpas** [comment]
What @Drofseh said, but without using the API function, those have extra safeties that we don't need to use, just using `ACRE_ACTIVE_RADIO == ""` would work, as it is set to `""` on `preInit` and nothing should ever set it to `nil`.

**Comment by jonpas** [comment]
Found an issue with this, does not reset when getting out of vehicle, stays hidden until user changes antenna position.

**Comment by jonpas** [comment]
Works nicely now, @PabstMirror if you want to give it another test, otherwise we can merge.

**Comment by PabstMirror** [comment]
Only because it's a everyFrame PFEH I switched it to a macro so we can skip 2 `params`

**Review by jonpas — APPROVED** [review]

**Pull request merged**
