### PR TITLE
Use isNotEqualTo

### PR DESCRIPTION
**Pull request by Neviothr**
**When merged this pull request will:**
- title

### CODE REVIEW

**Comment by jonpas** [comment]
Only on dev-branch.

**Comment by jonpas** [comment]
Added in 2.02.

**Comment by jonpas** [comment]
@Neviothr Should be tested and [requirement](https://github.com/IDI-Systems/acre2/blob/15dd4d836d896b8160f08b7fd55ae4db2678d945/addons/main/script_mod.hpp#L14) should be bumped.

**Comment by Neviothr** [comment]
I'm currently unable to test these changes. If anyone wants to pick up this PR, feel free.

**Review by jonpas — APPROVED** [review]

**Comment by jonpas** [comment]
`grep -Ri "!(.* isEqualTo .*)" addons/*/ | wc -l`
-> 0

**Pull request merged**
