### PR TITLE
Main - Matching case for case-sensitive keys

### PR DESCRIPTION
**Pull request by JonBons**
Fixes 152 referring to lowercase variants of hashmap keys

Still need to look into what to do to resolve the some of the issues brought up here: https://github.com/IDI-Systems/acre2/pull/1320#issuecomment-2040968335

### CODE REVIEW

**Comment by JonBons** [comment]
Need to change use of setVar and make sure this works correctly
https://github.com/IDI-Systems/acre2/blob/master/addons/sys_data/XEH_preInit.sqf#L40-L105

**Comment by JonBons** [comment]
List of hashmap key constants based on a case-sensitive deduplicated grep of the codebase (this does not include any keys from vars/macros or at runtime, will make an attempt to get this data later)

Used for HASH_SET:
```
1
acre_radioConnectionData
acre_radioState
active
allowed
anotherKey
audioPath
band
ch
channelKnobPosition
channelMode
channelNumber
channels
channelSpacing
channelSpacingKnobPosition
CTCSS
CTCSSRx
CTCSSTx
currentChannel
currentEditEntry
currentGroup
currentPreset
currentState
currentView
description
deviation
disabled
editEntry
encryption
entryCursor
fade
frequencies
frequencyRX
frequencyTX
function
functionKnobPosition
groups
isRadioRemovable
key
key1
kHzKnobPosition
label
lastActiveChannel
mainKnobPosition
manualChannelSelection
MemorySlotKnobPosition
menuIndex
menuPage
MHzKnobPosition
mode
modefunction
modulation
mountedRadio
name
networkID
NetworkKnobPosition
okRadios
on
optionCode
pgm_pa_mode
phase
playerRadios
power
powerSource
pressedButton
programmingStep
radioOn
RPTR
rxOnly
selectedEntry
shortName
squelch
syncLength
TEK
trafficRate
type
vehicle
volume
volumeKnobPosition
volumeModifier
wiredIntercoms
```

Used for HASH_GET:
```
ACRE_INTERNAL_RADIOSPATIALIZATION
acre_radioConnectionData
acre_radioState
active
audioPath
band
channelKnobPosition
channelMode
channels
CTCSS
CTCSSRx
CTCSSTx
currentChannel
description
deviation
encryption
fade
frequencies
frequencyRX
frequencyTX
groups
key
key1
kHzKnobPosition
label
manualChannelSelection
MHzKnobPosition
mode
modefunction
modulation
name
networkID
okRadios
on
optChannelData
optChannelId
optionCode
phase
playerRadios
power
powerSource
radioOn
RPTR
rxOnly
squelch
syncLength
TEK
trafficRate
volume
volumeModifier
```

**Comment by JonBons** [comment]
I'm shifting this into just being changes for mismatched case between getter/setter, I think this is most or all of the differences resolved.

It should be good to go with no dependencies on any other branch or commit.

**Comment by PabstMirror** [comment]
HEMTT 1.13 can now "optimize" away `toLower` and `toUpper` on string literals

so `#define HASH_GET(hash, key) (hash get toLower key)`
will have no runtime cost for many but not all uses

```
HASH_GET(_channel,"frequencyTX") // free - done at buildtime
HASH_GET(GVAR(callBacks),_id) // not free
```

**Review by jonpas — APPROVED** [review]

**Pull request merged**
