### PR TITLE
Components - Improve getAntennaDirMan function

### PR DESCRIPTION
**Pull request by PabstMirror**
- Fix dir vector flipping to wrong direction
- Fix dir/up not having diff angle of 90deg
- accurately rotate up vector when manually flipped up

Old code was generating forward/dir vector from
```
    private _forwardP = _upV call cba_fnc_vect2polar;
    _forwardP set [2, (_forwardP select 2) - 90];
    _forwardV = _forwardP call cba_fnc_polar2vect;
```
When leaning to the side this would cause the dir vector to rotate when it shouldn't
new: nF/nU in green,    old: oF,oU in red  (ups are identical in this case)
a

with antenna manually flipped up this could also cause the the dir to point backwards
b

This PR change the up calculation to rotate the spine direction based on a line between the two shoulders. The results won't be identical to the old way which added 50 degrees to the polar elevation. It also fixes some oddities when converting from AGL/ASL.

Demo code (3d stuff is hard to show in screenshots):
```
fnc_drawLineAndLabel = {
    params ["_uAGL", "_vAGL", "_color", "_txt"];
    drawLine3D [_uAGL, _vAGL, _color];
    drawIcon3D ["\a3\ui_f\data\gui\cfg\hints\icon_text\group_1_ca.paa", _color, _vAGL, 0.5, 0.5, 0, _txt, 2];
};
[{
    {
        private _obj = _x;
        private _spinePos = _obj modelToWorldVisual (_obj selectionPosition "Spine3");

        ([_x] call acre_sys_components_fnc_getAntennaDirMan) params ["_forwardV", "_upV"];
        private _oA = acos (_forwardV vectorCos _upV);
        [_spinePos, ASLtoAGL ((AGLtoASL _spinePos) vectorAdd _forwardV), [1,0,0,1], "oF"] call fnc_drawLineAndLabel;
        [_spinePos, ASLtoAGL ((AGLtoASL _spinePos) vectorAdd _upV), [1,0,0,1], "oU"] call fnc_drawLineAndLabel;

        ([_x] call fnc_antMan) params ["_forwardV", "_upV"];
        [_spinePos, ASLtoAGL ((AGLtoASL _spinePos) vectorAdd _forwardV), [0,1,0,1], "nF"] call fnc_drawLineAndLabel;
        [_spinePos, ASLtoAGL ((AGLtoASL _spinePos) vectorAdd _upV), [0,1,0,1], "nU"] call fnc_drawLineAndLabel;
        private _nA = acos (_forwardV vectorCos _upV);

        systemChat format ["up/dir angles %1 - %2", _oA, _nA];
    } forEach [player];
},0,[]] call CBA_fnc_addPerFrameHandler;

fnc_antMan = {
    params ["_obj"];

    private _spineVec = (_obj selectionPosition "Spine3") vectorFromTo (_obj selectionPosition "Neck");
    private _shoulderVec = (_obj selectionPosition "leftshoulder") vectorFromTo (_obj selectionPosition "rightshoulder");

    if (acre_sys_core_automaticAntennaDirection) then { // if (EGVAR(sys_core,automaticAntennaDirection)) then {
        private _spinePolar = _spineVec call cba_fnc_vect2polar;
        _spinePolar set [2, ((_spinePolar select 2) max 55) min 90];
        _spineVec = _spinePolar call cba_fnc_polar2vect;
    } else {
        if (_obj getVariable ["acre_sys_core_antennaDirUp", false]) then { // if (_obj getVariable [QEGVAR(sys_core,antennaDirUp), false]) then {
            _spineVec = [_spineVec, _shoulderVec, 55] call CBA_fnc_vectRotate3D;
        };
    };

    private _base = AGLtoASL (_obj modelToWorld [0,0,0]);
    _upV = _base vectorFromTo AGLtoASL (_obj ModelToWorld _spineVec);
    _forwardV = _spineVec vectorCrossProduct _shoulderVec; // will be normalized in next step
    _forwardV = _base vectorFromTo AGLtoASL (_obj ModelToWorld _forwardV);

    [_forwardV, _upV];
};
```

### CODE REVIEW

**Comment by jonpas** [comment]
Nice!

Is that demo code what you ended up committing or does it contain additional debug visualization? That might be good to add to the code base.

**Comment by PabstMirror** [comment]
It's based on `DRAW_ANTENNA_POS` that already existed
the demo code is meant to be run on current master/release so you see old and new at the same time

the biggest difference is going to be when 
- leaning
- antenna manually flipped up (and aiming semi-up)
- the slanted prone pose (z and then ctrl+a)

also bonus is it goes from 0.0388 ms -> 0.0184 ms

**Comment by Soldia1138** [comment]
Just added a small additional fix in documentation

**Review by Soldia1138 — APPROVED** [review]
Tested and works fine

**Comment by jonpas** [comment]
Let's merge after 2.7.3 release to not upset release drafter. :)

**Comment by Soldia1138** [comment]
Ready to merge? @jonpas

**Pull request merged**
