### PR TITLE
Disable performance counters

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Disables performance counters. 
- In Speaking function:
  - Average time lowered from 282.63 to 194.7 uS
  - Median time lowered from 161.00 to 147 uS

### CODE REVIEW

**Review by jonpas — APPROVED** [review]
Lovely!

**Comment by dedmen** [comment]
Why not just alter the `BEGIN_COUNTER`, `END_COUNTER` defines in one place, instead of putting ifdefs around them everywhere?
Just like ACE does.
https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/main/script_debug.hpp#L45

**Comment by jonpas** [comment]
@dedmen we do have that. Just talked with @TheMagnetar profiling was done with ASP, and that's the difference it has shown. Any clue why?

**Comment by dedmen** [comment]
>Any clue why?

Well I guess the defines are set even though they shouldn't be.
Have you checked the post-preprocess output to check whether the macros are defined although they shouldn't be?
Maybe someone is def'ing ENABLE_PERFORMANCE_COUNTERS before the script_debug.hpp include and undef'ing it again right after.

Maybe that difference is just in measurement tolerance, between Arma restarts things can change.
Have to check if the post-preprocess script really changed by making these changes, if it didn't change then obviously the measurements are just tolerance.

**Comment by jonpas** [comment]
I didn't check the output yet, I will when I get home. Nothing is defining it in-code that I could find.

It was tested a few times, all same results, tolerance like that wouldn't be consistent at all, definitely interesting.

**Pull request merged**
