### PR TITLE
Translations - Add French

### PR DESCRIPTION
**Pull request by Alfred-Neuman**
Translation french
last word left : IntCm

I don't know the French translation

### CODE REVIEW

**Comment by PabstMirror** [comment]
It's going to be a short version of the word "intercom"
looks like it needs to be 5 chars or less

**Comment by PabstMirror** [comment]
```
            <French>IntPh</French>
```
Would this work? (from Interphone)

**Review by PabstMirror — APPROVED** [review]
otherwise looks good

**Comment by Alfred-Neuman** [comment]
i have just add IntPh
I found it in some aeronautical docs
thanks for the idea

**Review by jonpas — APPROVED** [review]

**Pull request merged**
