### PR TITLE
Convert acre::Vector3 to a template

### PR DESCRIPTION
**Pull request by TheMagnetar**
**When merged this pull request will:**
- Title
- This is needed for later on.

### CODE REVIEW

**Review by jonpas — APPROVED** [review]

**Review by NouberNou — CHANGES_REQUESTED** [review]
We should pull up the specific type of the template into a typedef to avoid having to type the type out. That way if we ever wanted to use double precision (for some reason) we would just need to change the typedef.

**Comment by TheMagnetar** [comment]
What do you think of the following types?

```
using V3Float32_t = Vector3<float32_t>;
using V3Float64_t = Vector3<float64_t>;
```

**Comment by NouberNou** [comment]
Maybe vec3_float32 or vec3_fp32? v3 seems to ambiguous. I think it is more important to know the type of variable vs. it's precision of the constituent values.

**Comment by TheMagnetar** [comment]
I will go for vec3_fp32_t and vec3_fp64_t

**Review by NouberNou — APPROVED** [review]
Looks good.

**Pull request merged**
