### PR TITLE
GUI - Use XEH for inventory display initialization

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Use display XEH to initialize `RscDisplayInventory` instead of waiting for display to not be null after `InventoryOpened` event
- Use IDC defines from base game `defineResincl.inc` file

### CODE REVIEW

**Review by jonpas — APPROVED** [review]
Great!

**Comment by ThymoNL** [comment]
I can no longer build ACRE with this change due to `\a3\ui_f\hpp\defineResincl.inc` not existing.

**Comment by jonpas** [comment]
It was added in #963.

**Comment by ThymoNL** [comment]
That PR is not merged yet so merging this PR before that one breaks the master branch

**Comment by jonpas** [comment]
And that's fine, just grab the include from that one for the time being. Things don't move as fast as we would want.

**Pull request merged**
