### PR TITLE
Zeus - Radio Support

### PR DESCRIPTION
**Pull request by BrettMayson**
**When merged this pull request will:**
- Add radio support to both Zeus and Virtual Zeus

**TODO**
- [ ] Radio location
- [ ] Radio selection UI

### CODE REVIEW

**Comment by TheMagnetar** [comment]
Make use of ACRE_SPECTATOR_RADIOS array. It was introduced for these cases.

**Comment by Garfield0003** [comment]
Was looking for this sort of thing prior to raising a feature request. Is there any update on this? Appreciate that it has just missed the most recent release.
Or at this point, is it best to raise a new feature request?

**Comment by jonpas** [comment]
It is work in progress, a separate feature request would not be useful. :)

**Comment by BrettMayson** [comment]
Work in progress is a bit generous, I do want to wrap up my PRs. October is coming up..

**Comment by jonpas** [comment]
Don't think that one will count for October since you have to open it then. :P

**Comment by BrettMayson** [comment]
There are ways around that :p
And some of them are so old I am probably just going to start again off master, there wasn't much work done here and things have changed a bit since last year

**Comment by Garfield0003** [comment]
Thanks for the comments. Will keep an eye on this, as currently it is the main reason blocking my group from using ACRE as they use Zeus with virtual units.

**Comment by jonpas** [comment]
Any update on this @BrettMayson? If you will start off-master, can I close this PR?

**Pull request closed without merging**
